AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 Bucket and EC2 instance using parameter type keypair.

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.micro
      - t2.large
    Description: Select EC2 instance type
  EC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 key pair
    Default: iaccpk.pem

Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-97785bed                             # Replace with your Amazon Linux AMI ID
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref EC2KeyPair
  MyS3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: iacc-xxxxxxxx                         #Replace xxxxxx with your full name.